home:
  alias: '/basics'

pages:
  theme: learn3
  markdown:
    extra: true
  process:
    markdown: true
    twig: false
  hide_empty_folders: true

languages:
    supported: [15,16]
    pages_fallback_only: true

cache:
  enabled: true
  check:
    method: none
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
